{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "polymind.fullname" . }}
  labels:
    {{- include "polymind.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "polymind.selectorLabels" . | nindent 6 }}
  {{- with .Values.monitoring.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path | quote }}
      scheme: {{ .Values.monitoring.serviceMonitor.scheme | quote }}
      interval: {{ .Values.monitoring.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
