"""Workflow operations, not a generic repository or a queue authority.

Adapters must atomically enforce scope, state, lease/fence and cancellation on
mutations. A commit accepts one manifest and enables successors with their outbox
records in the same transaction. Implementations own time via an injected clock.
"""

from typing import Protocol
from uuid import UUID
from documents.models import ObjectRef, Scope
from documents.jobs.errors import Failure
from documents.jobs.models import Admission, Attempt, Dispatch, Job, Lease, Reconciliation, Step


class JobLedger(Protocol):
    def admit(self, request: Admission) -> Job: ...
    def get_job(self, scope: Scope, job_id: UUID) -> Job: ...
    def steps(self, scope: Scope, job_id: UUID) -> tuple[Step, ...]: ...
    def attempts(self, scope: Scope, job_id: UUID, step_id: UUID) -> tuple[Attempt, ...]: ...
    def claim(self, scope: Scope, job_id: UUID, step_id: UUID, owner: str) -> Lease | None: ...
    def renew(self, lease: Lease) -> None: ...
    def commit(self, lease: Lease, manifest: tuple[ObjectRef, ...]) -> Step: ...
    def fail(self, lease: Lease, failure: Failure) -> None: ...
    def cancel(self, scope: Scope, job_id: UUID) -> Job: ...
    def settle_cancel(self, lease: Lease) -> None: ...
    def register_object(self, lease: Lease, ref: ObjectRef) -> None: ...
    def pending_dispatch(self, limit: int = 100) -> tuple[Dispatch, ...]: ...
    def mark_delivered(self, dispatch: Dispatch) -> None: ...
    def reconcile(self, limit: int = 100) -> Reconciliation: ...
    def orphan_candidates(self, limit: int = 100) -> tuple[ObjectRef, ...]: ...
    def dead_letters(self, scope: Scope, job_id: UUID) -> tuple[dict, ...]: ...
